export enum BusinessEventType {
  // Inventory
  INVENTORY_LOW_STOCK = 'INVENTORY_LOW_STOCK',
  INVENTORY_OVERSTOCK = 'INVENTORY_OVERSTOCK',
  INVENTORY_STOCKOUT = 'INVENTORY_STOCKOUT',
  INVENTORY_SLOB_WARNING = 'INVENTORY_SLOB_WARNING',
  INVENTORY_NEGATIVE_STOCK = 'INVENTORY_NEGATIVE_STOCK',

  // Warehouse
  WAREHOUSE_DOCK_CONGESTION = 'WAREHOUSE_DOCK_CONGESTION',
  WAREHOUSE_PICKING_DELAY = 'WAREHOUSE_PICKING_DELAY',
  WAREHOUSE_RECEIVING_DELAY = 'WAREHOUSE_RECEIVING_DELAY',
  WAREHOUSE_CAPACITY_EXCEEDED = 'WAREHOUSE_CAPACITY_EXCEEDED',

  // Purchase
  PURCHASE_PO_DELAY = 'PURCHASE_PO_DELAY',
  PURCHASE_SUPPLIER_DELAY = 'PURCHASE_SUPPLIER_DELAY',
  PURCHASE_PRICE_INCREASE = 'PURCHASE_PRICE_INCREASE',
  PURCHASE_APPROVAL_TIMEOUT = 'PURCHASE_APPROVAL_TIMEOUT',

  // Sales
  SALES_ORDER_DELAY = 'SALES_ORDER_DELAY',
  SALES_SLA_BREACH = 'SALES_SLA_BREACH',
  SALES_BACKORDER_SURGE = 'SALES_BACKORDER_SURGE',
  SALES_REVENUE_DROP = 'SALES_REVENUE_DROP',

  // Finance
  FINANCE_CASH_FLOW_RISK = 'FINANCE_CASH_FLOW_RISK',
  FINANCE_BUDGET_VARIANCE = 'FINANCE_BUDGET_VARIANCE',
  FINANCE_PAYMENT_OVERDUE = 'FINANCE_PAYMENT_OVERDUE',
  FINANCE_MARGIN_REDUCTION = 'FINANCE_MARGIN_REDUCTION',

  // Customer
  CUSTOMER_COMPLAINT_SPIKE = 'CUSTOMER_COMPLAINT_SPIKE',
  CUSTOMER_CREDIT_LIMIT_EXCEEDED = 'CUSTOMER_CREDIT_LIMIT_EXCEEDED',
  CUSTOMER_HIGH_CHURN_RISK = 'CUSTOMER_HIGH_CHURN_RISK',

  // Supplier
  SUPPLIER_OTIF_DROP = 'SUPPLIER_OTIF_DROP',
  SUPPLIER_QUALITY_DEFECT_SPIKE = 'SUPPLIER_QUALITY_DEFECT_SPIKE',
  SUPPLIER_LEAD_TIME_DRIFT = 'SUPPLIER_LEAD_TIME_DRIFT',

  // Executive
  EXECUTIVE_KPI_BELOW_TARGET = 'EXECUTIVE_KPI_BELOW_TARGET',
  EXECUTIVE_RISK_ESCALATION = 'EXECUTIVE_RISK_ESCALATION',
  EXECUTIVE_CRITICAL_INCIDENT = 'EXECUTIVE_CRITICAL_INCIDENT',
}
